[package]
name = "sansio"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
bytes = "1.10.1"
clap = { version = "4.5.48", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
